### ISSUE TITLE
Style metadata example lacks dates

### ISSUE THREAD

**Issue by aaime** [cportele/t15-opf#1]
The conceptual model includes a set of possible dates, I don't see them in the API example.

Here is one way to encode them:

```
"dates": {
    "creation": "2019-01-01T10:05:00Z",
    "publication": "2019-01-01T11:05:00Z",
    "revision": "2019-02-01T11:05:00Z",
    "validTill": "2019-02-01T11:05:00Z",
    "receivedOn": "2019-02-01T11:05:00Z"
  }
```

As an alternative they could be top level attributes, with a bit more of verbosity:

```
   ....
    "creationDate": "2019-01-01T10:05:00Z",
    "publicationDate": "2019-01-01T11:05:00Z",
    "revisionDate": "2019-02-01T11:05:00Z",
    "validTill": "2019-02-01T11:05:00Z",
    "receivedOn": "2019-02-01T11:05:00Z"
```

**Comment by cportele** [comment]
Thanks, @aaime!

I have updated the style-metadata object and the example to include the dates property. 

I have used the first option (the object), but can easily change it to the second option, if this is preferred by the group.

**Comment by aaime** [comment]
Excellent, thank you!
